platform :ios, '5.0'
pod 'AFNetworking', '~> 1.3.0'
pod 'JSONKit'
pod 'MBProgressHUD', '~> 0.8'
pod 'ViewDeck'
pod 'OpenUDID'
pod 'SDWebImage'
pod 'TPKeyboardAvoiding'
pod 'TTTAttributedLabel'
pod 'Reachability'